---
driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  product_version: 16.0
  chef_license: accept
  client_rb:
    chef_license: accept 

verifier:
  name: inspec

platforms:
  - name: centos-7
  - name: ubuntu-16.04
  - name: windows-2016
    driver:
      box: tas50/windows_2016

suites:
  - name: default
    run_list:
      - recipe[github-runner-test::create_runner]
      - recipe[github-runner-test::delete_runner]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
